select * from emp;
/*
그룹함수: 데이터를 그룹별로 통계치를 처리할 때 활용된다.
sum() : 총합산.
/*
       숙제
         연봉단위별로 인원수 체크
         범위            사원수 (최고치, 최저치, 평균치)
         1000미만:       @@
         ~2000미만:      @@
         ~3000미만:      @@
         ~4000미만:      @@
         ~5000미만:      @@
         ~6000미만:      @@
	*/	 

SELECT TRUNC(SAL,-3)+1000||'미만: ', COUNT(TRUNC(SAL,-3)) FROM EMP
GROUP BY TRUNC(SAL,-3)
ORDER BY TRUNC(SAL,-3) DESC;	

SELECT TRUNC(SAL,-3), COUNT(SAL), MAX(SAL), AVG(SAL), MIN(SAL) FROM EMP
GROUP BY TRUNC(SAL,-3)
ORDER BY TRUNC(SAL,-3) DESC;


-- 정답 일듯..
SELECT TRUNC(SAL,-3)+1000||'미만:' "범위", COUNT(SAL), MAX(SAL), AVG(SAL), MIN(SAL) FROM EMP
GROUP BY TRUNC(SAL,-3)
ORDER BY TRUNC(SAL,-3) ASC;



SELECT * FROM EMP
WHERE SAL <3000 AND SAL >=2000;


	




SELECT ENAME, LOC 
FROM EMP, DEPT
WHERE EMP.DEPTNO = EMP.DEPTNO;



SELECT * FROM DEPT;
SELECT DISTINCT DEPTNO FROM EMP;



SELECT D.DEPTNO, D.DNAME, NVL(E.ENAME,'인원없음') ENAME
FROM EMP E, DEPT D
WHERE E.DEPTNO(+) = D.DEPTNO
ORDER BY E.DEPTNO;




SELECT * FROM EMP;
SELECT * FROM EMP WHERE JOB='MANAGER';


SELECT WORK.ENAME, WORK.MGR, MANAGER.ENAME
FROM EMP WORK, EMP MANAGER
WHERE WORK.MGR=MANAGER.EMPNO
ORDER BY MANAGER.EMPNO;



