CREATE TABLE QUIZBANK(
	QNUM NUMBER PRIMARY KEY,
	QUIZ VARCHAR2(1000),
	DINGDONG VARCHAR2(500),
	QUIZTYPE VARCHAR2(1)
);


CREATE SEQUENCE QUIZBANK_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999;
INSERT INTO QUIZBANK VALUES(QUIZBANK_SEQ.NEXTVAL,
	'싸움을 가장 잘하는 나라는?','칠레','S');
INSERT INTO QUIZBANK VALUES(QUIZBANK_SEQ.NEXTVAL,
	'슈퍼맨이 뉴욕 빌딩꼭대이에서 팔짱낀 이유?','손이시려워','S');
INSERT INTO QUIZBANK VALUES(QUIZBANK_SEQ.NEXTVAL,
	'이상한 사람들이 모이는 곳은?','치과','S');
INSERT INTO QUIZBANK VALUES(QUIZBANK_SEQ.NEXTVAL,
	'사람들이 가장 좋아하는 물은?','선물','S');

SELECT * FROM QUIZBANK;
