CREATE TABLE ACMEMBER (
	MCLASS NUMBER(5) NOT NULL,
	MNUM NUMBER(5) PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL UNIQUE,
	PASS VARCHAR2(50) NOT NULL,
	NIC VARCHAR2(50) UNIQUE,
	NAME VARCHAR2(50) NOT NULL,
	BIRTH DATE,
	EMAIL VARCHAR2(50),
	GRADE NUMBER(2) NOT NULL
);

INSERT INTO ACMEMBER VALUES
	(0, 1, 'admin', '11', '닉관리자', '관리자', NULL,'admin@why.not', 0);
	
INSERT INTO ACMEMBER VALUES
	(1, 10001, 'seller', '11', '닉판매자', '판매자', TO_DATE('1017-05-12', 'YYYY-MM-DD'), 'seller@why.not', 1);
	
INSERT INTO ACMEMBER VALUES
	(2, 20001, 'consumer', '11', '닉구매자', '구매자', TO_DATE('1017-05-31', 'YYYY-MM-DD'), 'consumer@why.not', 1);	
	
SELECT * FROM ACMEMBER;



CREATE TABLE ACPRODUCT(
	PNUM 



